export enum UserAuthzRefreshReason {
  LOGIN = 'LOGIN',
  REGISTER_SAAS_USER = 'REGISTER_SAAS_USER',
  REGISTER_CUSTOMER = 'REGISTER_CUSTOMER',
  REGISTER_CUSTOMER_OAUTH = 'REGISTER_CUSTOMER_OAUTH',
  REFRESH_TOKEN = 'REFRESH_TOKEN',

  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  USER_ADDED_TO_ORGANIZATION = 'USER_ADDED_TO_ORGANIZATION',
  USER_REMOVED_FROM_ORGANIZATION = 'USER_REMOVED_FROM_ORGANIZATION',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
}
